<center><h1>Преобразование признаков перед машинным обучением.</h1></center>

In [ ]:
%load_ext autoreload
%autoreload 2

import pandas as pd
import numpy as np

from feature_engineering import (
                                train_test,
                                OutsideInsideMetro          
                                )

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [3]:
data = pd.read_csv('/Users/muzaladinovdzamalladinruslanovic/Desktop/PROJECT CIAN/data/full data/cian_preprocessing.csv', index_col=0)
data.head()

,rooms,area,floor,floors_total,metro,metro_minutes,metro_transport,district,seller_type,price_rub
0,4.0,86.0,3,18,Корниловская,18.0,walk,Мосрентген,agency,26285040.0
1,1.0,33.4,2,9,Кокошкино,6.0,walk,Кокошкино,specialist,11000000.0
2,1.0,33.1,1,5,Щёлковская,7.0,walk,Северное Измайлово,specialist,12500000.0
3,1.0,41.3,25,27,Тушинская,8.0,transport,Покровское-Стрешнево,specialist,17500000.0
4,0.0,31.6,32,47,Печатники,13.0,walk,Печатники,agency,19842057.0

<h2>1. Деление выборки на train и test</h2>

In [9]:
X_train, X_test, y_train, y_test = train_test(data)
print(f'Train: {X_train.shape[0]} | Test: {X_test.shape[0]}')

Train: 18102 | Test: 7758

* выборка поделена на обучающую и тестовую.

<h2>2. Создание бинарного признака принадлежности к Москве</h2>

In [10]:
pd.DataFrame(X_train)

,rooms,area,floor,floors_total,metro,metro_minutes,metro_transport,district,seller_type
11913,4.0,90.00,1,10,Бунинская аллея,9.0,walk,Южное Бутово,specialist
8497,2.0,41.10,21,21,Чкаловская,2.0,walk,Басманный,agency
2455,3.0,83.90,32,53,Раменки,12.0,walk,Раменки,specialist
23336,3.0,93.00,11,14,Давыдково,4.0,transport,Можайский,specialist
4808,3.0,82.32,27,35,Сетунь,12.0,walk,Можайский,agency
...,...,...,...,...,...,...,...,...,...
21575,2.0,42.00,16,19,Потапово,9.0,transport,Сосенское,agency
5390,3.0,133.30,8,17,Терехово,7.0,transport,Хорошево-Мневники,agency
860,3.0,103.52,37,40,Минская,15.0,walk,Раменки,agency
15795,6.0,380.00,6,30,Новаторская,10.0,walk,Проспект Вернадского,agency
23654,2.0,147.00,6,7,Крылатское,6.0,transport,Крылатское,agency